src/main/resources/checkstyle.xml
=> Set allowed abbreviation length to default value (3) from 1.

pom.xml, src/main/resources/metadb_dependencies.properties
Signed-off-by: Divya Madala 71040191+divyamadala30@users.noreply.github.com
=> removed shared-entities dependency

pom.xml, src/main/java/org/mskcc/cmo/common/FileUtil.java, src/main/java/org/mskcc/cmo/common/impl/FileUtilImpl.java, src/main/resources/checkstyle.xml
=> Add FileUtil and impl class, update checkstyle xml

src/main/java/org/mskcc/cmo/common/impl/FileUtilImpl.java
=> Flush buffered writer

src/main/java/org/mskcc/cmo/common/enums/CmoSampleClass.java, src/main/java/org/mskcc/cmo/common/enums/NucleicAcid.java, src/main/java/org/mskcc/cmo/common/enums/Preservation.java, src/main/java/org/mskcc/cmo/common/enums/SampleOrigin.java, src/main/java/org/mskcc/cmo/common/enums/SampleType.java, src/main/java/org/mskcc/cmo/common/enums/SpecimenType.java, src/main/java/org/mskcc/cmo/common/enums/TumorNormalType.java
=> Standardize enum classes

pom.xml
=> Add checkstyle param to run check on test directory

src/main/java/org/mskcc/cmo/common/impl/MetadbJsonComparatorImpl.java
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
=> ignore cmoSampleName in MetadbJsonComparatorImpl

.github/release-drafter.yml, .github/workflows/release-management.yml
=> Add release management action

src/main/java/org/mskcc/cmo/common/impl/MetadbJsonComparatorImpl.java, src/test/resources/data/incoming_requests/mocked_request5_pt_multi_samples.json
- Updated ignored fields
- Minor changes to mocked request data for req #5
-- 
- [n/a] ~~Have unit tests been updated in relation to updates to the mocked test data?~~
If no unit tests were updated or added, then please explain …
=> Testing with Metadb refactored data parsing

src/main/java/org/mskcc/cmo/common/impl/MetadbJsonComparatorImpl.java, src/test/java/org/mskcc/cmo/metadb/MetadbJsonComparatorTest.java, src/test/resources/data/incoming_requests/mocked_request1_complete_tumor_normal.json, src/test/resources/data/incoming_requests/mocked_request1_updated_complete_tumor_normal.json, src/test/resources/data/incoming_requests/mocked_request2a_one_normal.json, src/test/resources/data/incoming_requests/mocked_request2b_missing_one_normal.json, src/test/resources/data/incoming_requests/mocked_request3_pooled_normals.json, src/test/resources/data/incoming_requests/mocked_request4_null_or_empty_values.json, src/test/resources/data/incoming_requests/mocked_request5_pt_multi_samples.json, src/test/resources/data/published_requests/outgoing_mocked_request1_complete_tumor_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request1_null_values.json, src/test/resources/data/published_requests/outgoing_mocked_request2a_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_all_pairs.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_missing_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request3_pooled_normals.json, src/test/resources/data/published_requests/outgoing_mocked_request4_null_or_empty_values.json
- Updated published request json to reflect the universal json schema
~- [ ] Has the consistency checking code been updated to handle new changes?~
~- [ ] Have unit tests been updated in relation to updates to the mocked test data?~
If no unit tests were updated or added, then please explain why: …
=> updated published request jsons to match the universal json schema

.github/PULL_REQUEST_TEMPLATE.md, src/test/resources/data/incoming_requests/mocked_request6_cmopt_after_swap.json, src/test/resources/data/incoming_requests/mocked_request6_cmopt_swap.json, src/test/resources/data/mocked_request_data_details.txt, src/test/resources/data/published_requests/outgoing_mocked_request1_complete_tumor_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request1_null_values.json
- Sample metadata now contains 'cmoSampleIdFields' in published mocked requests
as well as 'additionalProperties'
- Comparator has been updated to ignore the 'additionalProperties' field
- Additional mocked requests have been added
--- 
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more …
=> Updated mocked request data and comparator

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter.yml, pom.xml, src/main/java/org/mskcc/smile/commons/FileUtil.java, src/main/java/org/mskcc/smile/commons/JsonComparator.java, src/main/java/org/mskcc/smile/commons/enums/CmoSampleClass.java, src/main/java/org/mskcc/smile/commons/enums/NucleicAcid.java, src/main/java/org/mskcc/smile/commons/enums/Preservation.java, src/main/java/org/mskcc/smile/commons/enums/SampleOrigin.java, src/main/java/org/mskcc/smile/commons/enums/SampleType.java, src/main/java/org/mskcc/smile/commons/enums/SpecimenType.java, src/main/java/org/mskcc/smile/commons/enums/TumorNormalType.java, src/main/java/org/mskcc/smile/commons/impl/FileUtilImpl.java, src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java, src/test/java/org/mskcc/smile/commons/JsonComparatorTest.java, src/test/java/org/mskcc/smile/commons/config/MockDataConfig.java, src/test/java/org/mskcc/smile/commons/model/MockJsonTestData.java
- Refactored java packages/classes to SMILE
---
**Data checks:** `N/A`
**Code checks:** 
If no unit tests were updated or added, then please explain why: `N/A`
**Describe your testing environment:**
- NATS …
=> Smile renaming

.github/PULL_REQUEST_TEMPLATE.md, .github/release-drafter.yml, README.md, src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java, src/test/resources/data/other_mocked_data/outgoing_mocked_request1_updated_metadata.json, src/test/resources/data/published_requests/outgoing_mocked_request1_complete_tumor_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request1_null_values.json, src/test/resources/data/published_requests/outgoing_mocked_request2a_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_all_pairs.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_missing_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request3_pooled_normals.json, src/test/resources/data/published_requests/outgoing_mocked_request4_null_or_empty_values.json
- Changed metaDb* fields to smile* for SMILE internal ids
--- 
**Code checks:**
If no unit tests were updated or …
=> Update published fields metaDb --> smile

.github/PULL_REQUEST_TEMPLATE.md, src/test/resources/data/incoming_requests/mocked_request1_all_samples_missing_fastqs.json, src/test/resources/data/incoming_requests/mocked_request1_complete_tumor_normal.json, src/test/resources/data/incoming_requests/mocked_request1_sample_missing_fastqs.json, src/test/resources/data/incoming_requests/mocked_request1_updated_complete_tumor_normal.json, src/test/resources/data/incoming_requests/mocked_request1a_sample_type_abbreviation.json, src/test/resources/data/incoming_requests/mocked_request1b_nucleic_acid_abbreviation.json, src/test/resources/data/incoming_requests/mocked_request1c_missing_all_samples.json, src/test/resources/data/incoming_requests/mocked_request1d_missing_few_samples.json, src/test/resources/data/incoming_requests/mocked_request1e_null_string_baitset.json, src/test/resources/data/incoming_requests/mocked_request2a_one_empty_sample_metadata.json, src/test/resources/data/incoming_requests/mocked_request2a_one_normal.json, src/test/resources/data/incoming_requests/mocked_request2b_missing_one_normal.json, src/test/resources/data/incoming_requests/mocked_request3_pooled_normals.json, src/test/resources/data/incoming_requests/mocked_request4_null_or_empty_values.json, src/test/resources/data/incoming_requests/mocked_request5_pt_multi_samples.json, src/test/resources/data/incoming_requests/mocked_request6_cmopt_swap.json, src/test/resources/data/mocked_request_data_details.txt, src/test/resources/data/published_requests/outgoing_mocked_request1_complete_tumor_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request1_null_values.json, src/test/resources/data/published_requests/outgoing_mocked_request2a_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_all_pairs.json, src/test/resources/data/published_requests/outgoing_mocked_request2b_missing_one_normal.json, src/test/resources/data/published_requests/outgoing_mocked_request3_pooled_normals.json, src/test/resources/data/published_requests/outgoing_mocked_request4_null_or_empty_values.json
- Added files that were exclusive to the request filter (for provenance).
- Added new fields to sample-level data
--- 
**Code checks:**
- [n/a] ~~Unit tests were updated in relation to …
=> Mocked data synchronization and updates

src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java, src/test/java/org/mskcc/smile/commons/JsonComparatorTest.java, src/test/resources/data/mocked_request_data_details.txt, src/test/resources/data/published_requests/outgoing_mocked_request1_lib_update.json
Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
- Comparator now recognizes changes in libraries, qcReports and runs in SampleMetadata level
--- 
**Code …
=> Improved comparator

src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
Not assumed to always be part of a request json. Can sometimes be provided directly.
=> Handle scenario where sample metadata is compared directly

src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java, src/test/java/org/mskcc/smile/commons/JsonComparatorTest.java, src/test/resources/data/incoming_requests/mocked_request1_with_sample_status.json, src/test/resources/data/published_requests/outgoing_mocked_request1_invalid_sample_status.json, src/test/resources/data/published_requests/outgoing_mocked_request1_missing_sample_status.json, src/test/resources/data/published_requests/outgoing_mocked_request1_with_sample_status.json
- Status nodes are no longer in List.class format
- While filtering a status node, we now map it to Map.class
**Code checks:**
=> Compare Status as Map instead of List

src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java
- a
- b 
---
Fix # (see https://help.github.com/en/articles/closing-issues-using-keywords)
**Expected behavior**
**Actual behavior**
**Logs, error output, or stacktrace**
**Steps to reproduce the behavior**
**Tasks**
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at. 
--- 
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/ba …
=> modification to ignore list

pom.xml, src/main/java/org/mskcc/smile/commons/OpenTelemetryUtils.java, src/main/java/org/mskcc/smile/commons/impl/OpenTelemetryUtilsImpl.java
Using OTel trace propagator extension to support SMILE trace propagation over NATS messaging
=> otel b3 trace propagation support

src/main/java/org/mskcc/smile/commons/JsonComparator.java, src/main/java/org/mskcc/smile/commons/impl/JsonComparatorImpl.java, src/test/java/org/mskcc/smile/commons/JsonComparatorTest.java, src/test/java/org/mskcc/smile/commons/config/MockDataConfig.java, src/test/resources/data/mocked_request_data_details.txt, src/test/resources/data/tempo/bam_complete_MOCKREQUEST1_B_1.json, src/test/resources/data/tempo/bam_complete_MOCKREQUEST1_B_2.json, src/test/resources/data/tempo/bam_complete_MOCKREQUEST1_B_3.json, src/test/resources/data/tempo/bam_complete_MOCKREQUEST1_B_3_pass.json, src/test/resources/data/tempo/bam_complete_MOCKREQUEST1_B_4.json, src/test/resources/data/tempo/cohort_complete_CCS_PPPQQQQ.json, src/test/resources/data/tempo/cohort_complete_CCS_PPPQQQQ_2.json, src/test/resources/data/tempo/cohort_complete_CCS_PPPQQQQ_updated.json, src/test/resources/data/tempo/maf_complete_MOCKREQUEST1_B_1.json, src/test/resources/data/tempo/maf_complete_MOCKREQUEST1_B_2.json, src/test/resources/data/tempo/maf_complete_MOCKREQUEST1_B_3.json, src/test/resources/data/tempo/maf_complete_MOCKREQUEST1_B_3_pass.json, src/test/resources/data/tempo/maf_complete_MOCKREQUEST1_B_4.json, src/test/resources/data/tempo/mocked_tempo_data_details.txt, src/test/resources/data/tempo/qc_complete_MOCKREQUEST1_B_1.json, src/test/resources/data/tempo/qc_complete_MOCKREQUEST1_B_2.json, src/test/resources/data/tempo/qc_complete_MOCKREQUEST1_B_3.json, src/test/resources/data/tempo/qc_complete_MOCKREQUEST1_B_4.json
- Added new method for comparing generic jsons (not request or sample metadata)
- Added mocked test data for TEMPO jsons.
--- 
**Code checks:**
If no unit tests were updated or added, then please explain why: [insert details here]
**Describe your …
=> Added generic JSON comparator.
